### ISSUE TITLE
BadImageFormatException

### ISSUE THREAD

**Issue by magnusjjj** [nxrighthere/UnrealCLR#101]
LogUnrealCLR: Error: UnrealCLR::Module::Exception: Loading of assemblies failed
System.BadImageFormatException: Could not load file or assembly 'SkyrimPlug2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
File name: 'SkyrimPlug2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at UnrealEngine.Plugins.Loader.ManagedLoadContext.LoadAssemblyFromFilePath(String path) in E:\CSharp\UnrealEngine\Plugins\source\Loader\ManagedLoadContext.cs:line 194
   at UnrealEngine.Runtime.Core.ManagedCommand(Command command) in C:\Users\Tuxie\Downloads\UnrealCLR-master\Source\Managed\Runtime\Runtime.cs:line 267

Code is same as tutorial, the project file the same apart from referencing the assembly with a direct path. Checked both assemblies and as far as I could tell both were .net core 5.0.

**Comment by magnusjjj** [comment]
Upon looking closer at the exception after hunting around for a couple of hours before posting this, the 'reference assembly line' finally hit me.
The default compile generates a 'ref' directory. That directory includes a tiny .dll that is not an executable.

Maybe, hmm. Ignore those? Gonna see if I can't find the right directive to not generate it.

**Comment by magnusjjj** [comment]
<GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>

That stops the build. The default in vs2019 seems to be to build these references, that stops it :).

Sorry for the 'blogging', just took me wayyyy to long to figure out.

**Comment by magnusjjj** [comment]
`<GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>`
