### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by antidamage** [nxrighthere/UnrealCLR#255]
Installation fails:

`PS E:\Projects\xxx\Plugins\UnrealCLR\Install> dotnet run
Welcome to the UnrealCLR installation tool!

Please, set a path to an Unreal Engine project: E:\Projects\xxx\
Project file found in "E:\Projects\xxx" folder!

Do you want to compile and install tests? [y/n] y
Installation will delete all previous files of the plugin and content of tests. Do you want to continue? [y/n] y
Removing the previous plugin installation...
Unhandled exception. System.UnauthorizedAccessException: Access to the path 'Install.dll' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Install.Main(String[] arguments)`

I've run both with administrator privileges and without.  Authenticated users do have access to `Install.dll` in this location, so it's difficult to understand what's going wrong.

**Comment by nxrighthere** [comment]
Please, make sure that your anti-virus software is not blocking the installation tool.
