### ISSUE TITLE
An exception is thrown after plugin update

### ISSUE THREAD

**Issue by Richmet706** [nxrighthere/UnrealCLR#35]
Hi. I ran the install for the latest release successfully. When I try to run the scene I am getting an error. Did I mess up something with the install?
```
LogUnrealCLR: Error: UnrealCLR::Module::Exception: Loading of assemblies failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Cannot bind to the target method because its signature is not compatible with that of the delegate type.
   at System.Reflection.RuntimeMethodInfo.CreateDelegateInternal(Type delegateType, Object firstArgument, DelegateBindingFlags bindingFlags)
   at System.Reflection.RuntimeMethodInfo.CreateDelegate(Type delegateType)
   at UnrealEngine.Framework.Shared.Load(IntPtr* events, IntPtr functions, Assembly pluginAssembly) in C:\Users\richm\Documents\UnrealCLR\Source\Managed\Framework\Codegen.cs:line 1021
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at UnrealEngine.Runtime.Core.ManagedCommand(Command command) in C:\Users\richm\Documents\UnrealCLR\Source\Managed\Runtime\Runtime.cs:line 204
```

**Comment by nxrighthere** [comment]
Have you recompiled your project with an updated framework?

**Comment by nxrighthere** [comment]
Also, the compilation of assemblies during installation could be done incorrectly. Try to re-run installation if the recompilation of your .NET project doesn't help.

**Comment by Richmet706** [comment]
Thank you Stanislav. I got it working.
